// @ts-check
import js from '@eslint/js'
import tseslint from 'typescript-eslint'
import vue from 'eslint-plugin-vue'
import vueParser from 'vue-eslint-parser'
import prettierConfig from 'eslint-config-prettier'

export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/node_modules/**',
      '**/coverage/**',
      // Nuxt-generated files — not source, regenerated by `nuxi prepare`
      '**/.nuxt/**',
      '**/.output/**',
      // The playground app deliberately omits imports to exercise the
      // module's auto-import feature — ESLint's no-undef can't know about
      // that without pulling in the full @nuxt/eslint preset, so treat it
      // as covered by the e2e `nuxi build`/`nuxi dev` checks instead.
      'packages/*/playground/**',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  // 'essential' — correctness rules only. 'recommended' also enforces the
  // official Vue style guide's formatting rules (attribute-per-line, etc.);
  // formatting is Prettier's job (see .prettierrc.json), not the linter's.
  ...vue.configs['flat/essential'],
  // Turns off any remaining ESLint stylistic rules that could conflict with
  // Prettier's output — must stay after the presets above.
  prettierConfig,
  {
    files: ['**/*.vue'],
    languageOptions: {
      parser: vueParser,
      parserOptions: {
        parser: tseslint.parser,
        extraFileExtensions: ['.vue'],
      },
    },
  },
  {
    rules: {
      // Bracket-notation member access is used deliberately in the safe
      // expression parser (ConditionEvaluator) — not a stylistic choice.
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      'vue/multi-word-component-names': 'off',
      'no-console': 'off',
    },
  },
  {
    files: ['demo/**/*'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },
  {
    // Node CLI helper scripts (e.g. packages/nuxt/scripts/nuxi.mjs)
    files: ['**/scripts/**/*.mjs'],
    languageOptions: {
      globals: { process: 'readonly' },
    },
  },
)
